import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'







const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Strapi | Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
        <html lang="en">

          <body className={inter.className}>{children}
            <div className="main-container min-h-screen text-black dark:text-white-dark">
              
            </div>
          </body>
      </html>
    </>

  )
}
